README.md
Hi,
the npm badge currently shows a 404 image:
This PR fixes the badge link and it now returns:
=> readme: fix npm badge

.eslintrc, __tests__/components/TextOverlaySettingsBubble.test.js, src/components/TextOverlaySettingsBubble.js, src/index.js
As outlined in #12, this adds a progress indicator to the tool bubble and keeps it disabled while fetching external OCR texts.
=> Add 'fetching' indicator to tools bubble (#12)

src/components/PageTextDisplay.js
Previously we'd use a word's Y-Position and its height as the font-size in pixels. This led to a very irregular line appearance, since words consisting of all-lowercase letters would be rendered far too small.
With this change, we now use the line's Y-position and height instead, making for a far more regular line appearance, with no problems for selecting text.
=> Improve word rendering

__fixtures__/lines.json, __tests__/components/PageTextDisplay.test.js, __tests__/lib/ocrFormats.test.js, src/components/MiradorTextOverlay.js, src/components/PageTextDisplay.js, src/lib/ocrFormats.js
- **Don't render page text overlay when none of the lines have text.**
This fixes a bug with lazily loaded annotation texts in combination with the recent performance optimizations that resulted in text not being rendered.
-  **Don't show text until first transformation has been applied**
This prevents glitchy text display during page changes where there would be unscaled OCR text filling the screen for a few frames.
-  **Make sure the text parse always includes page dimensions.**
With the recent performance work, it has become mandatory that text parses contain their page's width and height. This commit adds a new source for those values in ALTO documents and adds a generic fallback heuristic to determine a rough page size from the coordinates of the text lines on the page.
- **Fix bug …
=> Fix regressions from performance refactor, more tests

src/components/PageTextDisplay.js
Previously we would alternate between rendering a line's box and a line's text. This would cause line boxes to overlap other line's text, rendering them less intelligible than when their texts overlapped:
This commit changes the code to first render all boxes and then render the line texts on top of that:
=> Improve line box rendering

__tests__/components/TextOverlaySettingsBubble.test.js, src/components/TextOverlaySettingsBubble.js, src/components/TextSelectIcon.js
Previously the colors were hard-coded to fit the default `light` theme, with this change we now adapt to the current theme's palette.
Example with `dark` theme before:
After this change:
=> Adapt settings bubble colors to theme

__tests__/components/PageTextDisplay.test.js, __tests__/components/TextOverlaySettingsBubble.test.js, __tests__/lib/color.js, __tests__/lib/color.test.js, __tests__/state/sagas.test.js, package.json, src/components/MiradorTextOverlay.js, src/components/PageTextDisplay.js, src/components/TextOverlaySettingsBubble.js, src/index.js, src/lib/color.js, src/locales.js, src/state/actions.js, src/state/reducers.js, src/state/sagas.js, src/state/selectors.js
Implements https://github.com/dbmdz/mirador-textoverlay/issues/23.
By default, the plugin will now try to determine the text and background colors from the page image.
It now also offers a color picker widget that allows users to pick a custom color for text and line background, which will override the automatically determined colors. There's also a button to reset the colors to the automatic colors.
[![IdioticRepulsiveAcornwoodpecker-mobile](https://user-images.githubusercontent.com/608610/88822636-67978580-d1c4-11ea-82c1-4ddbf4e094bb.jpg)](https://gfycat.com/idioticrepulsiveacornwoodpecker)
[click image for video of demo](https://gfycat.com/idioticrepulsiveacornwoodpecker)
The behavior can be configured with three new configuration keys:
- `useAutoColors`: Try do determine page colors …
=> Auto-select text and background colors, add color picker widget

src/components/MiradorTextOverlay.js, src/components/PageTextDisplay.js, src/index.js
Implements https://github.com/dbmdz/mirador-textoverlay/issues/24.
This PR modifies the overlay so it tracks the OSD viewport's rotation and flipping state (used in https://github.com/ProjectMirador/mirador-image-tools):
=> Track rotation and flipping of OSD viewport

src/components/PageTextDisplay.js
Previously we'd just change the cursor to `default`. This PR instead changes the `user-select` CSS property to `none` if text selection is disabled (`text` otherwise). This will also change the cursor, but also actually prevent the user from selecting text. Previously this would be a side-effect of us not stopping the `pointerDown` event from propagating to OSD, which caused issues on mobile, where a long-tap on e.g. Firefox would select the text even if selection was disabled.
=> Actually disable selection instead of just changing the cursor

src/components/MiradorTextOverlay.js
This caused the text to be visible despite the setting being `false`.
=> Zero-out opacity if visibility is disabled during viewport update

__tests__/components/PageTextDisplay.test.js, src/components/PageTextDisplay.js
On touch screens text selection is triggered by a long press, so we can let pointerdown events pass through to OSD if we detect one. This fixes problems with panning and zooming on mobile browsers when text selection was enabled.
=> Let pointerdown propagate if running on touch screen

__tests__/components/PageTextDisplay.test.js, src/components/PageTextDisplay.js
Rendering line rectangles first in the same SVG as the text broke cross-line selection behavior in WebKit-based browsers. This is now fixed by simply rendering the boxes in a separate SVG that is placed below the original SVG that now only contains the actual text.
<details>
<summary>Behavior before:</summary>
</details>
<details>
<summary>Behavior after:</summary>
</details>
=> Fix WebKit text selection bug by rendering rects in separate container

__fixtures__/lines.json, __tests__/components/PageTextDisplay.test.js, __tests__/lib/ocrFormats.test.js, src/components/MiradorTextOverlay.js, src/components/PageTextDisplay.js, src/lib/ocrFormats.js
Previously, we would add word tokens for space characters if an ALTO document encoded spaces, and otherwise expand existing words with whitespace if it didn't (always the case for hOCR).
This required a bunch of guesstimating and brittle hacks, so now we instead opt to use the space between existing words for whitespace uniformly.
This also renames `word` (which would now be misleading, since it can also contain only whitespace) to `span`.
=> Unify space handling between ALTO and hOCR.

README.md, src/components/MiradorTextOverlay.js, src/components/PageTextDisplay.js, src/state/selectors.js
Adds a new `fontFamily` configuration key that allows users to override the font used for rendering the text. The default font is now the font defined in the MaterialUI theme (or the user's theme, if provided in the Mirador config).
Allows things like this:
=> Make text font configurable, default to theme font

src/components/MiradorTextOverlay.js
This is achieved by a brutal hack (see docstring on `patchAnnotationOverlay`), but it works for:
- rendering search annotations
- rendering regular annotations
- editing annotations with the `mirador-annotations` plugin
To try it out, search for something in the "Wunder der Vererbung" manifest.
=> Fix interplay with annotation overlay (fixes #27)

__tests__/lib/ocrFormats.test.js, src/components/PageTextDisplay.js, src/lib/ocrFormats.js
hOCR lines that don't end on hyphenation now end correctly with a newline character in their last span's text.
Additionally, this commit improves whitespace rendering by setting the CSS `white-space` option to `pre`. This removes the ugly gaps between text-spans when selecting text.
=> Fix hOCR end-of-line whitespace handling

__tests__/components/MiradorTextOverlay.test.js, __tests__/components/PageTextDisplay.test.js, __tests__/utils.js, jest.config.js, src/components/PageTextDisplay.js
This adds tests for the last remaining untested component, bringing our line coverage to >85%.
=> Add tests for MiradorTextOverlay

__tests__/lib/color.test.js, package.json, src/components/PageTextDisplay.js, src/components/TextOverlaySettingsBubble.js, src/lib/color.js
Turns out MaterialUI already has code for changing a color's opacity, so we now just use that instead of our own custom code. Thanks to @mejackreed for pointing this out in another review!
=> Use MUI's fade function instead of custom changeAlpha

src/components/settings/ColorWidget.js, src/components/settings/OverlaySettings.js, src/index.js
This had the effect of making button popovers disappear in fullscreen mode, since the popovers would be  rendered as a child of the body element, which was not in fullscreen scope.
=> Add missing containerId prop to all MiradorMenuButton instances

__tests__/components/OverlaySettings.test.js, __tests__/state/sagas.test.js, src/state/actions.js, src/state/reducers.js, src/state/sagas.js
In this case, any modifications to the plugin state on the initial canvas would not cause the text for the canvases to be fetched. This was because we only triggered *discovery* of texts, but not
*fetching* for those that were already discovered, but not fetched.
=> Fix bug when initial plugin state is !visible && !selectable

__tests__/components/PageTextDisplay.test.js, src/components/PageTextDisplay.js
Previously this was disabled for mobile devices, since we wanted for the user to be able to pan and zoom the OSD canvas despite selection being enabled. It turns out that this was very wonky across browsers, so we've enabled event-swallowing again.
This has the effect that, if selection is enabled, panning and zooming has to be initiated on parts of the canvas that are not covered by text.
=> Always swallow pointerdown events if selection is enabled.

src/components/PageTextDisplay.js, src/components/settings/ColorInput.js
- Text selection was not working (`pointer-down` event is not supported in mobile Safari <13)
- Color pickers were not working (Safari ignored inputs that have `display: none`)
=> Fix Mobile Safari 12 issues

__fixtures__/hocr.html, __tests__/lib/ocrFormats.test.js, src/lib/ocrFormats.js
This is a workaround for wonky OCR files that contain whitespace with an effective width of zero.
This would cause the selected text to not contain any whitespace, since the corresponding SVG span would have a width of zero, leading to it not rendering. We work arorund this by ensuring that whitespace has at least a width of `0.0001`, which is large enough for browsers to take it into account for text selection, but small enough not to be noticeable.
=> Ensure that whitespace has a minimum width

src/state/selectors.js
This used to work, but when we fixed the case where only one of the
visible canvases had a text, we introduced a regression.
=> Hide settings bubble when no texts are available for visible canvases

src/lib/color.js
We now try to pick a color for the background (from the available colors on the page) that fulfills the WCAG required minimum contrast ratio of 7:1.
If none can be found, we pick white or black as a fallback, depending on the text color.
=> Make sure default text/bg colors are WCAG-compliant

src/lib/ocrFormats.js
Previously we'd use the unscaled page sizes as parsed from the OCR, which would lead to cases where the text would be only partially visible.
=> hocr: Scale page size according to scale factor

README.md, src/components/PageTextDisplay.js
This introduces a new theme section `textOverlay` that allows customization of the text selection foreground and background color, as well as the general font-family to use for rendering text.
This improves text selection aesthetics for hidden text in WebKit-based browsers, which did not display the selected text before. The default colors are dark blue with a white foreground, due to the WCAG-compliant contrast ratio of 7:1.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Add support for customizing selection colors.

.github/workflows/ci.yml
This PR adds `workflow_dispatch` so that CI can be started manually.
=> ci: allow to run ci manually
